# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_adminchat', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='chatsusuaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuaris', models.CharField(max_length=200)),
                ('id_chats', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='textchats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.CharField(max_length=200)),
                ('id_user', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('hora', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chats', models.CharField(max_length=200)),
                ('id_rols', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('cognoms', models.CharField(max_length=200)),
                ('correu', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
