# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chatsusuaris',
            new_name='Chatsusuari',
        ),
        migrations.RenameModel(
            old_name='textchats',
            new_name='Textchat',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
