# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_chat', '0003_auto_20161219_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chats',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='textchat',
            name='id_chat',
        ),
        migrations.RemoveField(
            model_name='textchat',
            name='id_user',
        ),
        migrations.AddField(
            model_name='textchat',
            name='nomchat',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='shoot_chat.Chat'),
        ),
        migrations.AddField(
            model_name='textchat',
            name='nomusuari',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='shoot_chat.User'),
        ),
    ]
