# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoot_chat', '0004_auto_20170116_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='id_adminchat',
        ),
        migrations.AddField(
            model_name='chat',
            name='adminchat',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='shoot_chat.User'),
        ),
    ]
